const type = $('#reviewApp').data('type')
const no = $('#reviewApp').data('no')
const sessionId = $('#id-div').data('userid')
let reviewApp=Vue.createApp({
	data(){
		return {
			type:type,
			no:no,
			list:[],
			curpage:1,
			totalpage:0,
			startPage:0,
			endPage:0,
			msg:'',
			sessionId:sessionId,
			isReply:false,
			rmsg:'',
			r:0,
			isUpdate:false,
			umsg:'',
			u:0
		}
	},
	mounted(){
		this.dataRecv()
	},
	methods:{
		dataRecv(){
			axios.get('../commons/review_list.do',{
				params:{
					page:this.curpage,
					no:this.no,
					type:this.type
				}
			}).then(res=>{
				console.log(res.data)
				this.list=res.data.list
				this.curpage=res.data.curpage
				this.totalpage=res.data.totalpage
				this.startPage=res.data.startPage
				this.endPage=res.data.endPage
			}).catch(error=>{
				console.log(error.response)
			})
		},
		prev(){
			this.curpage=this.curpage-1
			this.dataRecv()
		},
		next(){
			this.curpage=this.curpage+1
			this.dataRecv()
		},
		pageChange(i){
			this.curpage=i
			this.dataRecv()
		},
		range(start,end){
			let arr=[]
			let len=end-start
			for(let i=0;i<=len;i++){
				arr[i]=start
				start++
			}
			return arr
		},
		replyInsert(){
			if(this.msg===''){
				this.$refs.msg.focus()
				return
			}
			axios.post('../commons/review_insert.do',null,{
				params:{
					no:this.no,
					type:this.type,
					msg:this.msg,
					group_step:0
				}
			}).then(res=>{
				this.list=res.data.list
				this.curpage=res.data.curpage
				this.totalpage=res.data.totalpage
				this.startPage=res.data.startPage
				this.endPage=res.data.endPage
				this.msg=''
			}).catch(error=>{
				console.log(error.response)
			})
		},
		rReply(rno){
			$('.reply-div').hide()
			$('.btn-r').text('댓글')
			this.rmsg=''
			if(this.isReply){
				if(this.r==rno){
					this.isReply=false
					this.r=0
					$('#r'+rno).hide()
				}else{
					this.r=rno
					$('#btn-r'+rno).text('취소')
					$('#r'+rno).show()
				}
			}else{
				this.isReply=true
				this.r=rno
				$('#btn-r'+rno).text('취소')
				$('#r'+rno).show()
			}
		},
		rReplyInsert(rno){
			let idx=this.list.findIndex(r => r.rno == rno)
			if(this.rmsg===''){
				this.$refs.rmsg.focus()
				return
			}
			axios.post('../commons/review_insert.do',null,{
				params:{
					no:this.no,
					type:this.type,
					msg:this.rmsg,
					group_id:this.list[idx].group_id,
					group_step:1
				}
			}).then(res=>{
				this.list=res.data.list
				this.curpage=res.data.curpage
				this.totalpage=res.data.totalpage
				this.startPage=res.data.startPage
				this.endPage=res.data.endPage
				this.isReply=false
				$('.reply-div').hide()
				$('.btn-r').text('댓글')
				this.rmsg=''
				this.r=0
			}).catch(error=>{
				console.log(error.response)
			})
		},
		rUpdate(rno){
			let idx=this.list.findIndex(r => r.rno == rno)
			let m=this.list[idx].msg
			$('.update-div').hide()
			$('.btn-u').text('수정')
			this.umsg=''
			if(this.isUpdate){
				if(this.u==rno){
					this.isUpdate=false
					this.u=0
					$('#u'+rno).hide()
				}else{
					this.u=rno
					this.umsg=m
					$('#btn-u'+rno).text('취소')
					$('#u'+rno).show()
				}
			}else{
				this.isUpdate=true
				this.u=rno
				this.umsg=m
				$('#btn-u'+rno).text('취소')
				$('#u'+rno).show()
			}
		},
		uReplyUpdate(rno){
			if(this.umsg===''){
				this.$refs.umsg.focus()
				return
			}
			axios.post('../commons/review_update.do',null,{
				params:{
					no:this.no,
					type:this.type,
					rno:rno,
					msg:this.umsg
				}
			}).then(res=>{
				this.list=res.data.list
				this.curpage=res.data.curpage
				this.totalpage=res.data.totalpage
				this.startPage=res.data.startPage
				this.endPage=res.data.endPage
				this.isReply=false
				$('.update-div').hide()
				$('.btn-u').text('수정')
				this.umsg=''
				this.u=0
			}).catch(error=>{
				console.log(error.response)
			})
		},
		rDelete(rno){
			let idx=this.list.findIndex(r => r.rno == rno)
			let vo=this.list[idx]
			axios.get('../commons/review_delete.do',{
				params:{
					no:this.no,
					type:this.type,
					rno:rno,
					group_id:vo.group_id,
					group_step:vo.group_step
				}
			}).then(res=>{
				this.list=res.data.list
				this.curpage=res.data.curpage
				this.totalpage=res.data.totalpage
				this.startPage=res.data.startPage
				this.endPage=res.data.endPage
				this.isReply=false
				$('.update-div').hide()
				$('.btn-u').text('수정')
				this.umsg=''
				this.u=0
			}).catch(error=>{
				console.log(error.response)
			})
		}
	},
	components:{
		'page-card':page_card
	}
}).mount('#reviewApp')